### ISSUE TITLE
Some small glitches.

### ISSUE THREAD

**Issue by reggi** [sindresorhus/node-dark-mode#1]
What's happening for me:
- `isDark` doesn't work unless I set the bar to dark using either the CLI or the node module `dark-mode`.
- If I make the menu dark with the `use dark menu bar and dock` checkbox `isDark` returns false.
- If I do use `dark-mode` to make the menu dark the `use dark menu bar and dock` checkbox within the settings will be unresponsive.
- I must disable the dark menu via `dark-mode` in order to make the checkbox responsive again.

**Comment by sindresorhus** [comment]
Looks similar to https://github.com/samturner/lights-out/issues/4

The issue is most likely with though: https://github.com/sindresorhus/dark-mode

**Comment by sindresorhus** [comment]
Make sure you read: https://github.com/sindresorhus/dark-mode/releases/tag/2.0.0
